---
title: "s233374"
author: "Quim Bech Vilaseca"
format: html
editor: visual
---

# Lab 7 Exercises

## T1: Find the GitHub repository for the ggplot2 R-package

To search for that, we hae to go to the github page <https://github.com/>, login and then search in the search bar for ggplot2, which is going to redirect you into the next page: <https://github.com/tidyverse/ggplot2>.

### Q1: How many Contributors are there?

After getting into the page, we can search for the "Contributors" label, which is going to show us how many people work in this repository, we can see that there are +284 contributors!

## T1: Find the GitHub repository for the Linux kernel

Let's dive into this! For that, there is no straight forward page name, instead it is in the linux repository from torvalds showed here: <https://github.com/torvalds/linux>.

### Q2: How many Contributors are there?

There are many more than ggplot2! There are +14643 contributors.

### Q3: Discuss in your group why having an organised approach to version control is central? And consider the simple contrast of the challenges you were facing when doing the course assignments.
Mostly to synchronize the work done by multiple people on the same project.
That would be useful if we could work with that from the beginning since we've had troubles merging all the code we had.

Q4: Again, find the ggplot GitHub site and see if you can find how many branches there are?
There are 71 branches in ggplot Github.
















